version: "3"
services:
  web:
    image: playcassandraexample:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    stdin_open: true
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"